### PR TITLE
fix: fallback to CWD if automatic directory resolution fails

### LINKED ISSUE #32: Export to wezterm does not work
The call `lua require('highlite.export').wezterm('everforest')` causes error.
Export to `bat`, for example, works properly.

### PR DESCRIPTION
**Pull request by Iron-E**
Closes #32.

If a user does not specify the directory while exporting a colorscheme, nvim-highlite will attempt to resolve the proper directory. However, it seems that I did not implement proper error handling while writing this section of the code.

Now, if this happens, users will be informed that automatic resolution has failed, and that the program is falling back to the CWD.

### CODE REVIEW

File: lua/highlite/export/fish.lua [hunk 1]
```diff
@@ -57,11 +58,11 @@ local function export(colorscheme, opts, dir)
 	if opts == nil then opts = {} end
 
 	-- checked for backwards compatability
-	if dir == nil then
-		dir = opts.dir or (vim.fn.system({'fish', '-c', 'echo $__fish_config_dir/themes'}):sub(1, -2))
-	end
+	dir = Util.get_normalized_dir('bat', dir or opts.dir, function ()
```
Comment (Iron-E) [inline lua/highlite/export/fish.lua]: Should be `'fish'`

File: lua/highlite/export/native/lua.lua [hunk 2]
```diff
@@ -59,15 +60,14 @@ local function export(colorscheme, opts, dir)
 	if opts == nil then opts = {} end
 
 	-- checked for backwards compatability
-	if dir == nil then
-		dir = opts.dir or vim.fn.stdpath('config') .. '/colors/'
-	end
+	dir = Util.get_normalized_dir('bat', dir or opts.dir, function ()
```
Comment (Iron-E) [inline lua/highlite/export/native/lua.lua]: Should be `'neovim'`

File: lua/highlite/export/native/vim.lua [hunk 3]
```diff
@@ -120,15 +121,14 @@ local function export(colorscheme, opts, dir)
 	if opts == nil then opts = {} end
 
 	-- checked for backwards compatability
-	if dir == nil then
-		dir = opts.dir or vim.fn.stdpath('config') .. '/colors/'
-	end
+	dir = Util.get_normalized_dir('bat', dir or opts.dir, function ()
```
Comment (Iron-E) [inline lua/highlite/export/native/vim.lua]: Should be `'vim'`

File: lua/highlite/export/wezterm.lua [hunk 4]
```diff
@@ -104,14 +105,15 @@ local function export(colorscheme, opts, dir)
 	if opts == nil then opts = {} end
 
 	-- checked for backwards compatability
-	if dir == nil then
-		dir = opts.dir or vim.loop.os_getenv(vim.loop.os_uname().sysname == 'Windows' and
+	dir = Util.get_normalized_dir('bat', dir or opts.dir, function ()
```
Comment (Iron-E) [inline lua/highlite/export/wezterm.lua]: Should be `'wezterm'`

**Review by Iron-E — COMMENTED** [review]
Needs small changes before merge
